<!--
'*******************************************************************************************
' Transworld Interactive Projects - Version 2.7.2
' Written by Professor L. T. Kirby - Copyright 1998-2011 (c) Professor L. T. Kirby, Transworld Interactive. All Rights Reserved.
' This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 2.5 License. 
' To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-sa/2.5/ 
' or send a letter to Creative Commons, 543 Howard Street, 5th Floor, San Francisco, California, 94105, USA.
' All Copyright notices MUST remain in place at ALL times.
'******************************************************************************************** 
-->
<%
'This is the English Language File for Transworld Interactive Projects and may either 
'be named languages.asp or languagesEnglish.asp.  IF you would like the site to use English as 
'the language for the site and the existing languages.asp site is not in English then you will 
'need to rename the existing languages.asp site to something else and rename this file to 
'languages.asp

'if you translate this file into another language, please notify support@diggersolutions.com so 
'your translation can be made available to the community and can be included in the next version 
'release

dim dictLanguage  
set dictLanguage = CreateObject("Scripting.Dictionary")

dictLanguage.Add "Close_This_Window",	"Close this window"
dictLanguage.Add "Select",				"Select"
dictLanguage.Add "Add",					"Add"
dictLanguage.Add "Edit",				"Edit"
dictLanguage.Add "Delete",				"Delete"
dictLanguage.Add "Clients",				"Clients"
dictLanguage.Add "Projects",			"Projects"
dictLanguage.Add "Tasks",				"Tasks"
dictLanguage.Add "Timecards",			"Timecards"
dictLanguage.Add "Timesheets",			"Timesheets"
dictLanguage.Add "Reports",				"Reports"
dictLanguage.Add "Tools",				"Tools"
dictLanguage.Add "Logout",				"Logout"
dictLanguage.Add "Optional",			"optional"
dictLanguage.Add "Return_Business_Console", "Return to the Business Console"
dictLanguage.Add "ForgetPassword",		"Forget your Password?"
dictLanguage.Add "Password_Inst1",		"Forget your password?  Enter your email address " & _
	"on record and your user id and password will be emailed to you."
dictLanguage.Add "Password_Inst2",		"Your userid and password have been sent to your email address."
dictLanguage.Add "Error_PasswordNoEmail", "Please enter your email address."
dictLanguage.Add "Error_PasswordNoRecord", "There was no record with that email address.  Please try again."
dictLanguage.Add "Error_PasswordInactive", "The account associated with that email address is no longer active."
dictLanguage.Add "YourUserIDIs",		"Your user id is: "
dictLanguage.Add "YourPasswordIs",		"Your password is: "
		
'menus
dictLanguage.Add "New_Timecard",		"New Timecard"
dictLanguage.Add "View_My_Timecards",	"View My Timecards"
dictLanguage.Add "Work_Log_Internal",	"Work Log Internal"
dictLanguage.Add "Work_Log_For_Client",	"Work Log For Client"
dictLanguage.Add "Hourly_Timesheets",	"Hourly Timesheets"
dictLanguage.Add "New_Task",			"New Task"
dictLanguage.Add "View_Tasks",			"View Tasks"
dictLanguage.Add "View_My_Tasks",		"View My Tasks"
dictLanguage.Add "View_Tasks_I_Assigned", "View Tasks I Assigned"
dictLanguage.Add "New_Project",			"New Project"
dictLanguage.Add "View_Projects",		"View Projects"
dictLanguage.Add "Project_Status",		"Project Status"
dictLanguage.Add "Project_Quote",		"Project Quote"
dictLanguage.Add "Project_Quotes",		"Project Quotes"
dictLanguage.Add "Project_Dashboard",	"Project Dashboard"
dictLanguage.Add "New_Client",			"New Client"
dictLanguage.Add "View_Clients",		"View Clients"
dictLanguage.Add "View_My_Clients",		"View My Clients"
dictLanguage.Add "View_Client_Contact_Log", "View Client Contact Log"
dictLanguage.Add "Add_Log_Entry",		"Add Log Entry"
dictLanguage.Add "Options",				"Options"
	
'Admin Text
dictLanguage.Add "Admin",				"Admin"
dictLanguage.Add "Calendar",			"Calendar"
dictLanguage.Add "Database_Setup",		"Database Setup"   
dictLanguage.Add "Discussion_Forum",	"Discussion Forum"
dictLanguage.Add "Document_Repository", "Document Repository"
dictLanguage.Add "Employees",			"Employees"
dictLanguage.Add "Employee_Types",		"Employee Types"
dictLanguage.Add "Employee_Pay_Periods","Employee Pay Periods"
dictLanguage.Add "Timecard_Types",		"Employee Timecard Types"
dictLanguage.Add "News",				"News"
dictLanguage.Add "Project_Phases",		"Project Phases"
dictLanguage.Add "Surveys",				"Surveys"
dictLanguage.Add "Thoughts",			"Thoughts"
dictLanguage.Add "Workspace",			"Workspace"
dictLanguage.Add "Database_Export_Utils","Database &amp; Export Utilities"
dictLanguage.Add "Table_View",			"Table View"
dictLanguage.Add "Excel",				"Excel"
dictLanguage.Add "CDTF",				"Comma Delimited Text"
dictLanguage.Add "SQL_Query",			"SQL Query"
dictLanguage.Add "No_records_exist",	"No records exist in database."
dictLanguage.Add "Error_in_SQL",		"Error in the sql statement"

'## following section added in v2.6.1
'Admin/Site Configuration
dictLanguage.Add "Site_Configuration",	"Site Configuration"
dictLanguage.Add "Background",			"Background"
dictLanguage.Add "Highlight",			"Highlight"
dictLanguage.Add "Alt_Highlight",		"Alt Highlight"
dictLanguage.Add "Black",				"Black"
dictLanguage.Add "White",				"White"
dictLanguage.Add "Site_Name",			"Site Name"
dictLanguage.Add "Site_Logo",			"Site Logo"
dictLanguage.Add "Admin_Email",			"Admin Email"
dictLanguage.Add "Mail_Host",			"Mail Host"
dictLanguage.Add "Site_URL",			"Site URL"
dictLanguage.Add "Site_Root",			"Site Root"
dictLanguage.Add "Mail_Component",		"Mail Component"
dictLanguage.Add "Meta_Description",	"Meta Description"
dictLanguage.Add "Meta_Keywords",		"Meta Keywords"
dictLanguage.Add "Functionality_Options", "Functionality Options"
dictLanguage.Add "Home_Page_Options",	"Home Page Options"
dictLanguage.Add "Top_Nav",				"Top Nav"
dictLanguage.Add "DHTML_Nav",			"DHTML Nav"
dictLanguage.Add "Discussion",			"Discussion"
dictLanguage.Add "File_Repository",		"File Repository"
dictLanguage.Add "Auto_Login",			"Auto Login"
dictLanguage.Add "Show_Clients_in_Calendar", "Show Clients in Calendar"
dictLanguage.Add "Show_Projects_in_Calendar", "Show Projects in Calendar"
dictLanguage.Add "Show_Tasks_in_Calendar",	"Show Tasks in Calendar"
dictLanguage.Add "Host_Non_Billable",	"Host Non-Billable"
dictLanguage.Add "Send_Task_Emails",	"Send Tasks Emails"
dictLanguage.Add "Generate_Work_Order_Numbers", "Generate Work Order Numbers"
dictLanguage.Add "Top_Nav_Updated",		"The Top Navigation setting was updated."
dictLanguage.Add "Top_Nav_Not_Updated", "The Top Navigation setting was not updated: "
dictLanguage.Add "DHTML_Nav_Updated",	"The DHTML Navigation setting was updated."
dictLanguage.Add "DHTML_Nav_Not_Updated", "The DHTML Navigation setting was not updated: "
dictLanguage.Add "Timecards_Updated",	"The Timecards setting was updated."
dictLanguage.Add "Timecards_Not_Updated", "The Timecards setting was not updated: "
dictLanguage.Add "Tasks_Updated",		"The Tasks setting was updated."
dictLanguage.Add "Tasks_Not_Updated",	"The Tasks setting was not updated: "
dictLanguage.Add "Projects_Updated",	"The Projects setting was updated."
dictLanguage.Add "Projects_Not_Updated","The Projects setting was not updated: "
dictLanguage.Add "Clients_Updated",		"The Clients setting was updated."
dictLanguage.Add "Clients_Not_Updated",	"The Clients setting was not updated: "
dictLanguage.Add "Client_Contact_Log_Updated", "The Client Contact setting was updated."
dictLanguage.Add "Client_Contact_Log_Not_Updated", "The Client Contact setting was not updated: "
dictLanguage.Add "Timesheets_Updated",	"The Timesheets setting was updated."
dictLanguage.Add "Timesheets_Not_Updated", "The Timesheets setting was not updated: "
dictLanguage.Add "Project_Dashboard_Updated", "The Project Dashboard setting was updated."
dictLanguage.Add "Project_Dashboard_Not_Updated", "The Project Dashboard setting was not updated: "
dictLanguage.Add "Project_Quotes_Updated", "The Project Quotes setting was updated."
dictLanguage.Add "Project_Quotes_Not_Updated", "The Project Quotes setting was not updated: "
dictLanguage.Add "Host_Non_Billable_Updated", "The Host Non-Billable setting was updated."
dictLanguage.Add "Host_Non_Billable_Not_Updated", "The Host Non-Billable setting was not updated: "
dictLanguage.Add "Task_Emails_Updated",	"The Task Email setting was updated."
dictLanguage.Add "Task_Emails_Not_Updated",	"The Task Email setting was not updated: "
dictLanguage.Add "Dynamic_Work_Order_Number_Updated", "The Dynamic Work Order setting was updated."
dictLanguage.Add "Dynamic_Work_Order_Number_Not_Updated", "The Dynamic Work Order setting was not updated: "
dictLanguage.Add "Production_Report_Grid_Updated", "The Production Report Grid setting was updated."
dictLanguage.Add "Production_Report_Grid_Not_Updated", "The Production Report Grid setting was not updated: "
dictLanguage.Add "Reports_Updated",		"The Reports setting was updated."
dictLanguage.Add "Reports_Not_Updated",	"The Reports setting was not updated: "
dictLanguage.Add "Calendar_Updated",	"The Calendar setting was updated."
dictLanguage.Add "Calendar_Not_Updated","The Calendar setting was not updated: "
dictLanguage.Add "Discussion_Updated",	"The Discussion Board setting was updated."
dictLanguage.Add "Discussion_Not_Updated", "The Discussion Board setting was not updated: "
dictLanguage.Add "Employee_Directory_Updated", "The Employee Directory setting was updated."
dictLanguage.Add "Employee_Directory_Not_Updated", "The Employee Directory setting was not updated: "
dictLanguage.Add "File_Repository_Updated", "The File Repository setting was updated."
dictLanguage.Add "File_Repository_Not_Updated", "The File Repository setting was not updated: "
dictLanguage.Add "News_Updated",		"The News setting was updated."
dictLanguage.Add "News_Not_Updated",	"The News setting was not updated: "
dictLanguage.Add "Resources_Updated",	"The Resources setting was updated."
dictLanguage.Add "Resources_Not_Updated", "The Resources setting was not updated: "
dictLanguage.Add "Options_Updated",		"The Options setting was updated."
dictLanguage.Add "Options_Not_Updated",	"The Options setting was not updated: "
dictLanguage.Add "Auto_Login_Updated",	"The Auto Login setting was updated."
dictLanguage.Add "Auto_Login_Not_Updated", "The Auto Login setting was not updated: "
dictLanguage.Add "Calendar_Clients_Updated", "The Calendar Clients setting was updated."
dictLanguage.Add "Calendar_Clients_Not_Updated", "The Calendar Clients setting was not updated: "
dictLanguage.Add "Calendar_Projects_Updated", "The Calendar Projects setting was updated."
dictLanguage.Add "Calendar_Projects_Not_Updated", "The Calendar Projects setting was not updated: "
dictLanguage.Add "Calendar_Tasks_Updated", "The Calendar Tasks setting was updated."
dictLanguage.Add "Calendar_Tasks_Not_Updated", "The Calendar Tasks setting was not updated: "
dictLanguage.Add "Minimize_Maximize_Buttons", "Minimize/Maximize Buttons"
dictLanguage.Add "Production_Report",	"Production Report"
dictLanguage.Add "Survey",				"Survey"
dictLanguage.Add "External_News",		"External News"
dictLanguage.Add "External_News_World_News", "External News - World News"
dictLanguage.Add "External_News_US_News",	"External News - US News"
dictLanguage.Add "External_News_Tech_News",	"External News - Tech News"
dictLanguage.Add "External_News_Web_News", "External News - Web News"
dictLanguage.Add "External_News_Business_News", "External News - Business News"
dictLanguage.Add "External_News_Science_News", "External News - Science News"
dictLanguage.Add "External_News_Sports","External News - Sports"
dictLanguage.Add "External_News_Gaming","External News - Gaming"
dictLanguage.Add "External_News_Linux", "External News - Linux"
dictLanguage.Add "External_News_Linux_Gaming", "External News - Linux Gaming"
dictLanguage.Add "External_News_Linux_Software", "External News - Linux Software"
dictLanguage.Add "External_News_Mac",	"External News - Mac"
dictLanguage.Add "External_News_Mac_Gaming", "External News - Mac Gaming"
dictLanguage.Add "External_News_Mac_Software", "External News - Mac Software"
dictLanguage.Add "External_News_Show_Title", "External News - Show Title"
dictLanguage.Add "External_News_Show_Time",	"External News - Show Time"
dictLanguage.Add "External_News_Show_Indent", "External News - Show Indent"
dictLanguage.Add "External_News_Show_Number", "External News - Show Number"
dictLanguage.Add "External_News_Open_New_Window", "External News - Open New Window" 
dictLanguage.Add "Minimize_Maximize_Updated", "The Minimize/Maximize Buttons setting was updated."
dictLanguage.Add "Minimize_Maximize_Not_Updated", "The Minimize/Maximize Buttons setting was not updated: "
dictLanguage.Add "Thoughts_Updated",	"The Thoughts setting was updated."
dictLanguage.Add "Thoughts_Not_Updated","The Thoughts setting was not updated: "
dictLanguage.Add "Production_Report_Updated", "The Production Report setting was updated."
dictLanguage.Add "Production_Report_Not_Updated", "The Production Report setting was not updated: "
dictLanguage.Add "Survey_Updated",		"The Survey setting was updated."
dictLanguage.Add "Survey_Not_Updated",	"The Survey setting was not updated: "
dictLanguage.Add "External_News_Updated", "The External News setting was updated."
dictLanguage.Add "External_News_Not_Updated", "The External News setting was not updated: "
dictLanguage.Add "External_News_US_News_Updated", "The External News - US News setting was updated."
dictLanguage.Add "External_News_US_News_Not_Updated", "The External News - US News setting was not updated: "
dictLanguage.Add "External_News_World_News_Updated", "The External News - World News setting was updated."
dictLanguage.Add "External_News_World_News_Not_Updated", "The External News - World News setting was not updated: "
dictLanguage.Add "External_News_Web_News_Updated", "The External News - Web News setting was updated."
dictLanguage.Add "External_News_Web_News_Not_Updated", "The External News - Web News setting was not updated: "
dictLanguage.Add "External_News_Business_News_Updated", "The External News - Business News setting was updated."
dictLanguage.Add "External_News_Business_News_Not_Updated", "The External News - Business News setting was not updated: "
dictLanguage.Add "External_News_Tech_News_Updated", "The External News - Tech News setting was updated."
dictLanguage.Add "External_News_Tech_News_Not_Updated", "The External News - Tech News setting was not updated: "
dictLanguage.Add "External_News_Science_News_Updated", "The External News - Science News setting was updated."
dictLanguage.Add "External_News_Science_News_Not_Updated", "The External News - Science News setting was not updated: "
dictLanguage.Add "External_News_Sports_Updated", "The External News - Sports setting was updated."
dictLanguage.Add "External_News_Sports_Not_Updated", "The External News - Sports setting was not updated: "
dictLanguage.Add "External_News_Gaming_Updated", "The External News - Gaming setting was updated."
dictLanguage.Add "External_News_Gaming_Not_Updated", "The External News - Gaming setting was not updated: "
dictLanguage.Add "External_News_Linux_Updated", "The External News - Linux setting was updated."
dictLanguage.Add "External_News_Linux_Not_Updated", "The External News - Linux setting was not updated: "
dictLanguage.Add "External_News_Linux_Gaming_Updated", "The External News - Linux Gaming setting was updated."
dictLanguage.Add "External_News_Linux_Gaming_Not_Updated", "The External News - Linux Gaming setting was not updated: "
dictLanguage.Add "External_News_Linux_Software_Updated", "The External News - Linux Software setting was updated."
dictLanguage.Add "External_News_Linux_Software_Not_Updated", "The External News - Linux Software setting was not updated: "
dictLanguage.Add "External_News_Mac_Updated", "The External News - Mac setting was updated."
dictLanguage.Add "External_News_Mac_Not_Updated", "The External News - Mac setting was not updated: "
dictLanguage.Add "External_News_Mac_Gaming_Updated", "The External News - Mac Gaming setting was updated."
dictLanguage.Add "External_News_Mac_Gaming_Not_Updated", "The External News - Mac Gaming setting was not updated: "
dictLanguage.Add "External_News_Mac_Software_Updated", "The External News - Mac Software setting was updated."
dictLanguage.Add "External_News_Mac_Software_Not_Updated", "The External News - Mac Software setting was not updated: "
dictLanguage.Add "External_News_Show_Title_Updated", "The External News - Show Title setting was updated."
dictLanguage.Add "External_News_Show_Title_Not_Updated", "The External News - Show Title setting was not updated: "
dictLanguage.Add "External_News_Show_Time_Updated", "The External News - Show Time setting was updated."
dictLanguage.Add "External_News_Show_Time_Not_Updated", "The External News - Show Time setting was not updated: "
dictLanguage.Add "External_News_Show_Indent_Updated", "The External News - Show Indent setting was updated."
dictLanguage.Add "External_News_Show_Indent_Not_Updated", "The External News - Show Indent setting was not updated: "
dictLanguage.Add "External_News_Show_Number_Updated", "The External News - Show Number setting was updated."
dictLanguage.Add "External_News_Show_Number_Not_Updated", "The External News - Show Number setting was not updated: "
dictLanguage.Add "External_News_Show_New_Window_Updated", "The External News - Show New Window setting was updated."
dictLanguage.Add "External_News_Show_New_Window_Not_Updated", "The External News - Show New Window setting was not updated: "
dictLanguage.Add "Select_Color",		"Select Color"
dictLanguage.Add "The_setting_was_updated", "The setting was updated."
dictLanguage.Add "Site_Config_Not_Found", "The SiteConfig.asp file was not where it was expected.  Please check that the site has been configured properly."

'Admin/Calendar Text
dictLanguage.Add "Add_New_Event",		"Add Event"
dictLanguage.Add "Edit_Event",			"Edit Event"
dictLanguage.Add "Confirm_Delete_Event","Are you sure you want to delete this event?"
dictLanguage.Add "Delete_Event",		"Delete Event"   
dictLanguage.Add "Search_Events",		"Search Events"
dictLanguage.Add "Start_Date",			"Start Date"
dictLanguage.Add "End_Date",			"End Date"
dictLanguage.Add "Add_Event",			"Add Event"
dictLanguage.Add "Event_ID",			"Event ID"
dictLanguage.Add "Event_Date",			"Event Date"
dictLanguage.Add "Event_Start_Time",	"Event Start Time"
dictLanguage.Add "Event_End_Time",		"Event End Time"
dictLanguage.Add "Heading",				"Heading"
dictLanguage.Add "Abstract",			"Abstract"	
dictLanguage.Add "Event_Details",		"Event Details"
dictLanguage.Add "Live",				"Live"	
dictLanguage.Add "Event_Added",			"The event was added."
dictLanguage.Add "Event_Updated",		"The event was updated."
dictLanguage.Add "Event_Deleted",		"The event was deleted."
dictLanguage.Add "Return_Admin_Home",	"Return to Admin Home"	
	
'Admin/DB Setup
dictLanguage.Add "dbsetup1",			"You have either just created this site or you " & _
	"are attempting to change the database configuration.  Please do not change these if " & _
	"you are not the administrator of this site.  Select the type of database that you are " & _
	"using for this site - default is the Access file that shipped with this product. " & _
	"After selecting the type you will be prompted to enter specific connection parameters. " & _ 
	"For the default use of Access just keep hitting continue."	
dictLanguage.Add "Other",				"Other"
dictLanguage.Add "dbsetup2",			"Since you indicated that your database is not " & _
	"Access or SQL Server you will have to manually setup the database configuration " & _
	"in the <b>SiteConfig.asp</b> page located in the includes folder of the site."	
dictLanguage.Add "dbsetup3",			"Please enter the name of the Access database " & _
	"file (.mdb) below.  The default file that ships with this product is intranet.mdb. " & _
	"The file should be placed in the data folder in the root of the site. " 
dictLanguage.Add "Access_File_Name",	"Access File Name"
dictLanguage.Add "dbsetup4",			"Please enter the configuration information for " & _
	"the Sql Server database that you will be using for this product." 
dictLanguage.Add "Data_Source",			"Data Source (Server Name)"
dictLanguage.Add "Initial_Catalog",     "Initial Catalog (Database Name)"
dictLanguage.Add "User_Name",			"User Name"
dictLanguage.Add "Password",			"Password"
dictLanguage.Add "dbsetup5",			"Your database has been configured.  If " & _
	"everything has worked as it should you will be able to go to the login page " & _
	"and login with a username and password you have previously setup or with the " & _
	"default username of &quot;user&quot; and password of &quot;pass&quot;."
dictLanguage.Add "Proceed_To_Login",	"Proceed to the Login Page"	
	
'Admin/Employees
dictLanguage.Add "Employee",			"Employee"
dictLanguage.Add "Add_New_Employee",	"Add Employee"
dictLanguage.Add "Edit_Employee",		"Edit Employee"
dictLanguage.Add "Edit_Permissions",	"Edit Permissions"
dictLanguage.Add "Employee_ID",			"Employee ID"
dictLanguage.Add "Name",				"Name"
dictLanguage.Add "Title",				"Title"
dictLanguage.Add "Login",				"Login"
dictLanguage.Add "Initials",			"Initials"
dictLanguage.Add "Image",				"Image"
dictLanguage.Add "Email",				"Email"
dictLanguage.Add "Alt_Email",			"Alt Email"
dictLanguage.Add "IM_Name",				"IM Name"
dictLanguage.Add "Commission_Percentage", "Commission Percentage"
dictLanguage.Add "Monthly_Sales_Goal",	"Monthly Sales Goal"
dictLanguage.Add "Monthly_Production_Goal", "Monthly Production Goal"
dictLanguage.Add "Hourly",				"Hourly"
dictLanguage.Add "Active",				"Active"
dictLanguage.Add "Employee_Type",		"Employee Type"
dictLanguage.Add "Department",			"Department"
dictLanguage.Add "Reports_To",			"Reports To"
dictLanguage.Add "Birth_Date",			"Birth Date"
dictLanguage.Add "Phone",				"Phone"
dictLanguage.Add "Home_Phone",			"Home Phone"
dictLanguage.Add "Mobile_Phone",		"Mobile Phone"
dictLanguage.Add "Work_Phone",			"Work Phone"
dictLanguage.Add "ext.",				"ext."
dictLanguage.Add "Voice_Mail",			"Voice Mail"
dictLanguage.Add "Home_Address",		"Home Address"
dictLanguage.Add "City",				"City"
dictLanguage.Add "State",				"State"
dictLanguage.Add "Zip",					"Zip"
dictLanguage.Add "Current_Image",		"Current Image"
dictLanguage.Add "New_Image",			"New Image"
dictLanguage.Add "All_Permissions",		"All Permissions"
dictLanguage.Add "Admin_Permissions",	"Admin Permissions"	
dictLanguage.Add "Add_Messages",		"Add Messages"
dictLanguage.Add "Upload_Documents",	"Upload Documents"
dictLanguage.Add "Permissions_Updated",	"The employee's permissions were updated."
dictLanguage.Add "Upload_Error_1",		"There was an error in the web application.  The file was not uploaded properly<br>"
dictLanguage.Add "Upload_Error_2",		"The file was not uploaded properly: <br>"
dictLanguage.Add "Employee_Added",		"The employee was added."		
dictLanguage.Add "Employee_Updated",	"The employee was updated."
dictLanguage.Add "EmployeesPerms",		"Employees Permissions"
dictLanguage.Add "Inactive",			"Inactive"	
	
'Admin/forums
dictLanguage.Add "Click_Here_To_Add",	"Click here to add a forum"
dictLanguage.Add "No_Forums_Open",		"There are no forums currently open."
dictLanguage.Add "Post_Message_To",		"Post a New Message to "
dictLanguage.Add "Forum_Name",			"Forum Name"
dictLanguage.Add "Description",			"Description"
dictLanguage.Add "The_Forum",			"The Forum"
dictLanguage.Add "Has_Been_Created",	"has been created"
dictLanguage.Add "Back_To_Forums",		"Back To Forum Admin"
dictLanguage.Add "Add_Forum",			"Add Forum"
dictLanguage.Add "Delete_Forum",		"Delete Forum"
dictLanguage.Add "deleteforum_1",		"Are you sure you wish to delete the forum:"
dictLanguage.Add "deleteforum_2",		"And all the messages it contains?"
dictLanguage.Add "Forum_Deleted",		"The Forum has been deleted."
dictLanguage.Add "Update_Forum",		"Update Forum"
dictLanguage.Add "updateforum_1",		"Please enter the Forum ID number to Update"
dictLanguage.Add "Forum_Updated",		"The Forum has been updated"
dictLanguage.Add "Confirm_Delete_Forum","This will permanently DELETE the record from the database.\nAre you sure you want to continue? \n\n"
dictLanguage.Add "Post_A_Reply",		"Post a Reply"
dictLanguage.Add "Back_To_The_Folder",  "Back to the Forum"	
dictLanguage.Add "Delete_Message",		"Delete Message"
dictLanguage.Add "Modify_Message",		"Modify Message"
dictLanguage.Add "Unable_To_Locate_Msg","Unable to locate that message!"
dictLanguage.Add "Post_Message",		"Post Message"
dictLanguage.Add "Edit_Message",		"Edit Message"
dictLanguage.Add "Subject",				"Subject"
dictLanguage.Add "Message",				"Message"
dictLanguage.Add "Message_Updated",		"The message has been updated"
dictLanguage.Add "Back_To_Message",		"Back to Message"
	
'Admin/News
dictLanguage.Add "Search_News",			"Search News"
dictLanguage.Add "News_ID",				"News ID"
dictLanguage.Add "News_Date",			"News Date"
dictLanguage.Add "Details",				"Details"
'## following line added in v2.6.0
dictLanguage.Add "Source",				"Source"
	
'Admin/EmployeeTypes
dictLanguage.Add "Add_Emp_Type",		"Add Employee Type"
dictLanguage.Add "Edit_Emp_Type",		"Edit Employee Type"
dictLanguage.Add "Delete_Emp_Type",		"Delete Employee Type"
dictLanguage.Add "Confirm_Delete_Emp_Type", "Are you sure you want to delete this employee type?"
dictLanguage.Add "Employee_Type_ID",	"Employee Type ID"
dictLanguage.Add "Rate",				"Rate"
dictLanguage.Add "Cost",				"Cost"
dictLanguage.Add "Integer",				"integer"
dictLanguage.Add "Added_Emp_Type",		"The Employee Type was added."
dictLanguage.Add "Updated_Emp_Type",	"The Employee Type was updated."
dictLanguage.Add "Deleted_Emp_Type",	"The Employee Type was deleted."
	
'Admin/PayPeriods
dictLanguage.Add "Add_Pay_Period",		"Add Pay Period"
dictLanguage.Add "Edit_Pay_Period",		"Edit Pay Period"
dictLanguage.Add "Delete_Pay_Period",	"Delete Pay Period"
dictLanguage.Add "Confirm_Delete_Pay_Period", "Are you sure you want to delete this pay period?"
dictLanguage.Add "Pay_Period_ID",		"Pay Period ID"
dictLanguage.Add "Added_Pay_Period",	"The Pay Period was added."
dictLanguage.Add "Updated_Pay_Period",	"The Pay Period was updated."
dictLanguage.Add "Deleted_Pay_Period",	"The Pay Period was deleted."
	
'Admin/ProjectPhases
dictLanguage.Add "Add_Project_Phase",	"Add Project Phase"
dictLanguage.Add "Edit_Project_Phase",	"Edit Project Phase"
dictLanguage.Add "Delete_Project_Phase","Delete Project Phase"
dictLanguage.Add "Confirm_Delete_Project_Phase", "Are you sure you want to delete this phase?"
dictLanguage.Add "Project_Phase_ID",	"Project Phase ID"
dictLanguage.Add "Project_Phase_Name",	"Project Phase Name"
dictLanguage.Add "Added_Project_Phase",	"The Project Phase was added."
dictLanguage.Add "Updated_Project_Phase", "The Project Phase was updated."
dictLanguage.Add "Deleted_Project_Phase", "The Project Phase was deleted."
	
'Admin/TimecardTypes
dictLanguage.Add "Add_Timecard_Type",	"Add Timecard Type"
dictLanguage.Add "Edit_Timecard_Type",	"Edit Timecard Type"
dictLanguage.Add "Delete_Timecard_Type","Delete Timecard Type"
dictLanguage.Add "Confirm_Delete_Timecard_Type", "Are you sure you want to delete this timecard type?"
dictLanguage.Add "Timecard_Type_ID",	"Timecard Type ID"
dictLanguage.Add "Timecard_Type",		"Timecard Type"
dictLanguage.Add "Default_Employee_Type", "Default Employee Type"
dictLanguage.Add "Added_Timecard_Type",	"The Timecard Type was added."
dictLanguage.Add "Updated_Timecard_Type", "The Timecard Type was updated."
dictLanguage.Add "Deleted_Timecard_Type", "The Timecard Type was deleted."
	
'Admin/DocRep
dictLanguage.Add "Document",			"Document"
dictLanguage.Add "Add_Document",		"Add Document"
dictLanguage.Add "Edit_Document",		"Edit Document"
dictLanguage.Add "Delete_Document",		"Delete Document"
dictLanguage.Add "Confirm_Delete_Document", "Are you sure you want to delete this document?"
dictLanguage.Add "Confirm_Delete_Folder", "Are you sure you want to delete this folder\n and all sub-folders?"
dictLanguage.Add "Folder_Empty",		"The Folder is Empty."
dictLanguage.Add "DocRepInst_1",		"Select the category for your document or " & _
	"URL from the drop-down list. Then use the ""Browse"" button to locate the " & _
	"data file or enter the URL into the provided field and click ""Submit"" to " & _
	"upload it to the server.  Please use the full URL, including the ""http://""."
dictLanguage.Add "DocRepInst_2",		"Select the action you would like to " & _
	"perform (add/edit/delete) by clicking on one of the Icons "
dictLanguage.Add "DocRepInst_3",		"next to the document or folder you wish " & _
	"to perform an action on.  If you need to add a top level folder or a new " & _
	"document, click the add icon in the blue header area."
dictLanguage.Add "Contact",				"Contact"
dictLanguage.Add "Folder",				"Folder"
dictLanguage.Add "File_Path",			"File Path"
dictLanguage.Add "OR",					"OR"
dictLanguage.Add "URL",					"URL"
dictLanguage.Add "No_Document_Found",	"No Document Found"
dictLanguage.Add "Folder_Name",			"Folder Name"
dictLanguage.Add "Edit_Folder",			"Edit Folder"
dictLanguage.Add "Delete_Folder",		"Delete Folder"
dictLanguage.Add "Add_Folder",			"Add Folder"
dictLanguage.Add "Add_SubFolder",		"Add SubFolder"
dictLanguage.Add "SubFolder_Of",		"SubFolder Of"
dictLanguage.Add "None_TopLevelFolder", "None - this is a top level folder"
dictLanguage.Add "No_Folder_Found",		"No Folder Found"
dictLanguage.Add "Added_Document",		"The document was added."
dictLanguage.Add "Updated_Document",	"The document was updated."
dictLanguage.Add "Deleted_Document",	"The document was deleted."
dictLanguage.Add "Added_Folder",		"The folder was added."
dictLanguage.Add "Updated_Folder",		"The folder was updated."
dictLanguage.Add "Deleted_Folder",		"The folder wad deleted."
dictLanguage.Add "NoDeleted_Document",	"Sorry, You do not have permissions to delete that document."
dictLanguage.Add "NoDeleted_Folder",	"Sorry, you do not have permissions to delete that folder."	
dictLanguage.Add "Error_FileExists",	"A file already exists by that name.  Please rename it and try again."
dictLanguage.Add "Error_NoFileInput",	"You must include a file or a URL"
dictLanguage.Add "Document_Uploaded",	"Your document was submitted to the repository."
dictLanguage.Add "Folders",				"Folders"

'Admin/Survey
dictLanguage.Add "Error_No_Answer",		"Please enter the answer"	
dictLanguage.Add "Error_No_Question",	"Please enter the question"
dictLanguage.Add "Error_No_Topic",		"Please enter the Survey Topic"
dictLanguage.Add "Answer",				"Answer"
dictLanguage.Add "Question",			"Question"
dictLanguage.Add "Return_Survey_Admin_Home", "Return to the Survey Admin Home"
dictLanguage.Add "Click_Delete_Answer", "Click here to delete the answer."
dictLanguage.Add "Click_Delete_Question", "Click here to delete the question."
dictLanguage.Add "Confirm_Delete_Answer", "Are you sure you want to delete this answer?"
dictLanguage.Add "Confirm_Delete_Question", "Are you sure you want to delete this question?"
dictLanguage.Add "Confirm_Delete_Survey", "Are you sure you want to delete this survey?"
dictLanguage.Add "Active_Survey_Is",	"The active survey is"
dictLanguage.Add "No_Active_Survey",	"No Active Survey"
dictLanguage.Add "Choose_Survey",		"Choose Survey"
dictLanguage.Add "Survey_Is_Active",	"The survey you selected is now the active survey"
dictLanguage.Add "Survey_Is_Deleted",	"The survey you selected has been deleted"
dictLanguage.Add "Active_Survey",		"Active Survey"
dictLanguage.Add "Active_Survey_Results", "Active Survey Results"
dictLanguage.Add "Detailed_Survey_Results", "Detailed Survey Results"
dictLanguage.Add "Change_Active_Survey","Change Active Survey"
dictLanguage.Add "Add_Survey",			"Add Survey"
dictLanguage.Add "Edit_A_Survey",		"Edit a Survey"
dictLanguage.Add "Delete_Survey",		"Delete Survey"
dictLanguage.Add "Type",				"Type"
dictLanguage.Add "Radio_Buttons",		"Radio Buttons"
dictLanguage.Add "Checkboxes",			"Checkboxes"
dictLanguage.Add "Text_Field",			"Text Field"
dictLanguage.Add "Label",				"Label"
dictLanguage.Add "Survey_Topic",		"Survey Topic"
dictLanguage.Add "SurveyInst_1",		"The survey has been entered.<br>To add " & _
	"questions and answers to the survey click "
dictLanguage.Add "Here",				"here"
dictLanguage.Add "SurveyInst_2",		"select the survey and begin adding"
dictLanguage.Add "SurveyInst_3",		"It is not a good idea to edit a survey " & _
	"after it has been made active.  Doing so may make the results unreliable."
dictLanguage.Add "No_Questions_Entered","No questions have been entered for this survey"
dictLanguage.Add "Add_Answer",			"Add an Answer"
dictLanguage.Add "Add_Question",		"Add a Question"
dictLanguage.Add "Entry",				"Entry"
dictLanguage.Add "Entry_Date",			"Entry Date"
dictLanguage.Add "Origin_IP_Address",	"Origin IP Address"
dictLanguage.Add "Email_Address",		"Email Address"
dictLanguage.Add "Replies",				"Replies"
	
'Admin/Thoughts
dictLanguage.Add "Add_A_Thought",		"Add a Thought"
dictLanguage.Add "Confirm_Delete_Thought", "Are you sure you want to delete this thought?"
dictLanguage.Add "Return_Thoughts_Admin_Home", "Return to Thoughts Admin Home"
dictLanguage.Add "Thought",				"Thought"
dictLanguage.Add "Edit_Thought",		"Edit Thought"
dictLanguage.Add "Thought_Thanks",		"Thank You. Your changes have been made."
	
'Calendar
dictLanguage.Add "Previous_Day",		"Previous Day"
dictLanguage.Add "Next_Day",			"Next Day"
dictLanguage.Add "more",				"more"
dictLanguage.Add "No_Events_Scheduled", "No events scheduled for "
dictLanguage.Add "Sun",					"Sun"
dictLanguage.Add "Mon",					"Mon"
dictLanguage.Add "Tue",					"Tue"
dictLanguage.Add "Wed",					"Wed"
dictLanguage.Add "Thu",					"Thu"
dictLanguage.Add "Fri",					"Fri"
dictLanguage.Add "Sat",					"Sat"
'# following lines added in version 2.7.1
dictLanguage.Add "Month_View",			"Month View"
dictLanguage.Add "Week_View",			"Week View"
dictLanguage.Add "Day_View",			"Day View"
dictLanguage.Add "Click_For_Full_View", "Click for Full View"
	
'Clients
dictLanguage.Add "Client_Contact_Log",	"Client Contact Log"
dictLanguage.Add "Rep",					"Rep"
dictLanguage.Add "Client",				"Client"
dictLanguage.Add "spoke_to",			"spoke to"
dictLanguage.Add "Date_Of_Call",		"Date of Call"
dictLanguage.Add "Time_Of_Call",		"Time of Call"
dictLanguage.Add "Client_Details",		"Client Details"
dictLanguage.Add "Required_Items",		"required items"
dictLanguage.Add "Client_Rep",			"Client Rep"
dictLanguage.Add "Client_Since",		"Client Since"
dictLanguage.Add "Standard_Rate",		"Standard Rate"
dictLanguage.Add "Address_1",			"Address 1"
dictLanguage.Add "Address_2",			"Address 2"
dictLanguage.Add "Web_Site_URL",		"Web Site URL"
dictLanguage.Add "Contact_Name",		"Contact Name"
dictLanguage.Add "Contact_Phone",		"Contact Phone"
dictLanguage.Add "Contact_Email",		"Contact Email"
dictLanguage.Add "Contact_2_Name",		"Contact 2 Name"
dictLanguage.Add "Contact_2_Phone",		"Contact 2 Phone"
dictLanguage.Add "Contact_2_Email",		"Contact 2 Email"
dictLanguage.Add "Notes",				"Notes"
dictLanguage.Add "Error_No_ClientName", "Please enter a name for the client"
dictLanguage.Add "Error_No_ClientRep",	"Please select a Rep"
dictLanguage.Add "Error_No_ClientStart","Please enter the client since date"
dictLanguage.Add "Error_Invalid_ClientStart", "Please enter a valid date for the client since date"
dictLanguage.Add "Error_No_ClientRate",	"Please enter the standard rate"
dictLanguage.Add "Error_Invalid_ClientRate", "Please enter a valid number for the standard rate"
dictLanguage.Add "Added_Client",		"The Client Was Added Successfully"
dictLanguage.Add "Add_Client",			"Add a Client"
dictLanguage.Add "No_Client_ID",		"No clients found with that id"
dictLanguage.Add "Updated_Client",		"The Client Was Updated Successfully"
dictLanguage.Add "View",				"View"
dictLanguage.Add "All",					"All"
dictLanguage.Add "View_All_Clients",	"View All Clients"
dictLanguage.Add "View_Active_Clients",	"View Active Clients"
dictLanguage.Add "Account_Rep",			"Account Rep"
dictLanguage.Add "Select_Client_Log",	"Select a Client Communication Log"
dictLanguage.Add "Add_Message",			"Add a Message"
dictLanguage.Add "Client_Name",			"Client Name"
dictLanguage.Add "Date",				"Date"
dictLanguage.Add "Time",				"Time"
dictLanguage.Add "Spoke_To",			"Spoke To"
dictLanguage.Add "View_All_My_Clients", "View All My Clients"
dictLanguage.Add "View_My_Active_Clients", "View My Active Clients"
	
'Employees
dictLanguage.Add "Employee_Directory",	"Employee Directory"
dictLanguage.Add "Business_Details",	"Business Details"
dictLanguage.Add "Personal_Details",	"Personal Details"
dictLanguage.Add "Edit_My_Profile",		"Edit My Profile"
dictLanguage.Add "Return_Employee_Directory", "Return to the Employee Directory"
dictLanguage.Add "Click_Printable_Emp_Directory", "Click here for Printable Contact Directory"
dictLanguage.Add "Employee_Contact_Directory", "Employee Contact Directory"
dictLanguage.Add "B-Day",				"B-Day"
dictLanguage.Add "Work",				"Work"
dictLanguage.Add "Home",				"Home"
dictLanguage.Add "Mobile",				"Mobile"
dictLanguage.Add "Address",				"Address"
dictLanguage.Add "Updated_Profile",		"Your profile was updated."
dictLanguage.Add "Feature_EmpAdminPak", "This feature is available with the Transworld Interactive Employee Admin Pak"
	
'Forum
dictLanguage.Add "Moderate_Forum",		"Moderate Forum"
dictLanguage.Add "Forum_Code_Based",	"Forum code based on"
dictLanguage.Add "Display_Message",		"Display Message"
dictLanguage.Add "Author",				"Author"
dictLanguage.Add "Search_Results",		"Search Results"
dictLanguage.Add "Your_Search_Returned","Your search returned "
dictLanguage.Add "matches",				" matches"
dictLanguage.Add "Page",				"Page"
dictLanguage.Add "of",					"of"
dictLanguage.Add "No_Messages_Found",	"No Messages Found"
dictLanguage.Add "Result_Pages",		"Result Pages"
dictLanguage.Add "Prev",				"Prev"
dictLanguage.Add "Next",				"Next"
dictLanguage.Add "Refine_Your_Search",  "Refine Your Search"
dictLanguage.Add "Advanced_Search",		"Advanced Search"
dictLanguage.Add "messages",			"messages"
dictLanguage.Add "messages_pending_approval", "messages pending approval"
dictLanguage.Add "replies",				"replies"
dictLanguage.Add "Thank_You_Post",		"Thank you for your post!"
dictLanguage.Add "View_Your_Message",	"View Your Message"
dictLanguage.Add "Back_To_The_Message",	"Back to the Message"
dictLanguage.Add "Error_NoActiveForum",	"You aren't in an active forum!"
dictLanguage.Add "Error_InvalidThread", "Invalid thread information!"
dictLanguage.Add "Error_ForumEmptyName","Name can't be empty!"
dictLanguage.Add "Error_ForumEmptySubject", "Subject can't be empty!"
dictLanguage.Add "Error_ForumMsgEmpty", "Message can't be empty!"
dictLanguage.Add "Forum_EmailMe",		"Email me when someone posts a new message in this thread."
dictLanguage.Add "contains",			"contains"
dictLanguage.Add "is_exactly",			"is exactly"
dictLanguage.Add "all_words",			"all words"
dictLanguage.Add "Posted_Between",		"Posted between"
dictLanguage.Add "Body",				"Body"
dictLanguage.Add "and",					"and"
dictLanguage.Add "Error_NoValue",		"Please enter a value"
dictLanguage.Add "Search_Forum_Keyword","Search the forums for a keyword"
dictLanguage.Add "posts",				"posts"
	
'Document repository
dictLanguage.Add "Repository_Menu",		"Repository Menu"
dictLanguage.Add "Browse_Folders",		"Browse Folders"
dictLanguage.Add "Search_Documents",	"Search Documents"
dictLanguage.Add "Upload_Document",		"Upload Document"

'## following line added in version 2.6.2 for addition of inventory
'Inventory
dictLanguage.Add "Inventory",			"Inventory"

	
'Main Pages
dictLanguage.Add "Collapse_This_Window","Collapse This Window"
dictLanguage.Add "Open_This_Window",	"Open This Window"
dictLanguage.Add "Todays_Date",			"Today's Date"
dictLanguage.Add "Logged_In",			"Logged In"
dictLanguage.Add "Error_NotLoggedIn",	"You are currently not logged in or your " & _
	"login has timed out.<br>Please login to continue your session. Sorry for any inconvenience."
dictLanguage.Add "Intranet_Login",		"Project Manager Login"
dictLanguage.Add "ID",					"ID"
dictLanguage.Add "Error_NoUserID",		"Oops, you didn't enter your User ID."
dictLanguage.Add "Error_NoUser",		"We couldn't find User ID"
dictLanguage.Add "Please_Try_Again",	"Please Try Again."
dictLanguage.Add "Error_InvalidPass",	"Oops! Your User ID is okay, but the Password didn't work."
dictLanguage.Add "Error_InactiveAcct",	"Inactive or Expired Account"
dictLanguage.Add "User",				"User"
dictLanguage.Add "logged_on",			"logged on"
dictLanguage.Add "click",				"click"
dictLanguage.Add "here",				"here"
dictLanguage.Add "logon_diff_user",		"to logon as a different user"	
dictLanguage.Add "Error_LoggedTwice",	"You've already logged in and out twice today."
dictLanguage.Add "Error_NoThoughtsExist", "You must enter your thoughts for them to display!!!"
dictLanguage.Add "Clock_In",			"Clock In"
dictLanguage.Add "Clock_Out",			"Clock Out"
dictLanguage.Add "THINK_OF_THIS",		"THINK OF THIS"
dictLanguage.Add "NEWS",				"NEWS"
dictLanguage.Add "NEW_DISCUSSION_TOPICS", "NEW DISCUSSION TOPICS"
dictLanguage.Add "PRODUCTION_REPORT",	"PRODUCTION REPORT"
dictLanguage.Add "TIMECARDS",			"TIMECARDS"
dictLanguage.Add "TASKS",				"TASKS"
dictLanguage.Add "PROJECTS",			"PROJECTS"
dictLanguage.Add "CLIENTS",				"CLIENTS"
dictLanguage.Add "TOOLS",				"TOOLS"
dictLanguage.Add "CALENDAR",			"CALENDAR"
dictLanguage.Add "SURVEY",				"SURVEY"
dictLanguage.Add "NEWS_FEED",			"NEWS FEED"
'## following line added in version 2.6.0
dictLanguage.Add "RESOURCES",			"RESOURCES"
dictLanguage.Add "Team_Monthly_Prod_Goal", "Team Monthly Production Goal"
dictLanguage.Add "We_Are_Currently_At", "We are currently at"
dictLanguage.Add "We_Need",				"We need"
dictLanguage.Add "We_Are",				"We are"
dictLanguage.Add "Over_Our_Goal",		"over our goal. Great job"
dictLanguage.Add "Personal_Monthly_Prod_Goal", "Personal Monthly Production Goal"
dictLanguage.Add "You_Are_Currently_At","You are currently at"
dictLanguage.Add "You_Need",			"You need"
dictLanguage.Add "You_Are",				"You are"
dictLanguage.Add "Over_Your_Goal",		"over your goal. Great job"
dictLanguage.Add "Hours_Today",			"hours so far today"
dictLanguage.Add "Hours_Yesterday",		"entered for yesterday"
dictLanguage.Add "New",					"New"
			
'Projects
dictLanguage.Add "Select_Project_For_Dashboard", "Select Project for Dashboard"
dictLanguage.Add "Select_Project",		"Select Project"
dictLanguage.Add "Project",				"Project"
dictLanguage.Add "Edit_Client",			"Edit Client"
dictLanguage.Add "Edit_Project",		"Edit Project"
dictLanguage.Add "Work_Order",			"Work Order"
dictLanguage.Add "Status",				"Status"
dictLanguage.Add "B",					"B"
dictLanguage.Add "A",					"A"
dictLanguage.Add "R",					"R"
dictLanguage.Add "Core_Team",			"Core Team"
dictLanguage.Add "Total",				"Total"
dictLanguage.Add "Phase",				"Phase"
dictLanguage.Add "Hours_Used",			"Hours Used"
dictLanguage.Add "Invalid_Project",		"Invalid Project"
dictLanguage.Add "Project_Documents",	"Project Documents"
dictLanguage.Add "Click_Doc_Rep",		"Click to go to Document Repository"
dictLanguage.Add "Click_Discussion_Forum", "Click to go to Discussion Forum"
dictLanguage.Add "Date_Submitted",		"Date Submitted"
dictLanguage.Add "No_Project_Documents","No Document Folder for this Project"
dictLanguage.Add "No_Project_Discussion", "No Discussion Forum for this project."
dictLanguage.Add "Project_Discussion",	"Project Discussion"
dictLanguage.Add "Project_Tasks",		"Project Tasks"
dictLanguage.Add "Done",				"Done"
dictLanguage.Add "Date_Due",			"Date Due"
dictLanguage.Add "Priority",			"Priority"
dictLanguage.Add "Created_By",			"Created By"
dictLanguage.Add "Assigned_To",			"Assigned To"
dictLanguage.Add "Est_Hours_Left",		"Est Hours Left"
dictLanguage.Add "Est_Total_Hours",		"Est Total Hours"
dictLanguage.Add "Date_Created",		"Date Created"
dictLanguage.Add "Active_Tasks",		"Active Tasks"
dictLanguage.Add "Inactive_Tasks",		"Inactive Tasks"
dictLanguage.Add "Undelete",			"Undelete"
dictLanguage.Add "Confirm_Task_Delete", "Are you sure you want to delete this task?"
dictLanguage.Add "Confirm_Task_Restore","Are you sure you want to activate this task?"
dictLanguage.Add "Low",					"Low"
dictLanguage.Add "Medium",				"Medium"
dictLanguage.Add "High",				"High"
dictLanguage.Add "On_Hold",				"On Hold"
dictLanguage.Add "Project_Timecards",	"Project Timecards"
dictLanguage.Add "Billable",			"Billable"
dictLanguage.Add "Non-Billable",		"Non-Billable"
dictLanguage.Add "Comments",			"Comments"
dictLanguage.Add "No",					"No"
dictLanguage.Add "Yes",					"Yes"
dictLanguage.Add "None",				"None"
dictLanguage.Add "Project_Details",		"Project Details"
dictLanguage.Add "Project_Type",		"Project Type"
dictLanguage.Add "Green",				"Green"
dictLanguage.Add "Red",					"Red"
dictLanguage.Add "Blue",				"Blue"
dictLanguage.Add "Hours",				"Hours"
dictLanguage.Add "Team_Member",			"Team Member"
dictLanguage.Add "Error_ProjectNoName", "Please give the project a name"
dictLanguage.Add "Error_ProjectNoClient", "Please choose a Client for the project"
dictLanguage.Add "Error_ProjectInactiveClient", "The Client you have selected is " & _
	"not active.<br>In order to enter a project for this client, you must first " & _
	"make the client active"	
dictLanguage.Add "Error_ProjectNoRep",	"Please select an Account Rep"
dictLanguage.Add "Error_ProjectNoWO",	"Please enter a work order number"
dictLanguage.Add "Error_ProjectNoStart","Please enter the project start date"
dictLanguage.Add "Error_ProjectInvalidStart", "Please enter a valid start date"
dictLanguage.Add "Error_ProjectNoEnd",	"Please enter the project end date"
dictLanguage.Add "Error_ProjectInvalidEnd", "Please enter a valid end date"
dictLanguage.Add "Error_ProjectNoType", "Please select a project type"
dictLanguage.Add "Added_Project",		"The Project Was Added Successfully"
dictLanguage.Add "Add_Project",			"Add a Project"
dictLanguage.Add "True",				"True"
dictLanguage.Add "False",				"False"
dictLanguage.Add "Updated_Project",		"The Project Was Updated Successfully"
dictLanguage.Add "All_Active_Projects", "All Active Projects"
dictLanguage.Add "View_All_Projects",	"View All Projects"
dictLanguage.Add "View_Active_Projects","View Active Projects"
dictLanguage.Add "Print_This_Summary",	"Print this Summary"
dictLanguage.Add "No_Projects_For_Type","No Projects exist for the project type"
dictLanguage.Add "Date_Quote_Prepared", "Date Quote Prepared"
dictLanguage.Add "Create_Project_Quote","Create Project Quote"
dictLanguage.Add "Existing_Project_Quotes", "Existing Project Quotes"
	
'## folowing section added in Version 2.7.2
'PTO
dictLanguage.Add "PTO",					"PTO"
dictLanguage.Add "PTO_Admin",			"PTO Admin"
dictLanguage.Add "Initiate_PTO_Request","Initiate PTO Request"
dictLanguage.Add "Preliminary_PTO_Form","Preliminary PTO Form"
dictLanguage.Add "View_PTO_Requests",   "View PTO Requests"
dictLanguage.Add "PTO_Form",			"PTO Form"
dictLanguage.Add "Start_Time",			"Start Time"
dictLanguage.Add "End_Time",			"End Time"
dictLanguage.Add "Paid",				"Paid"
dictLanguage.Add "Current_PTO_Balance",	"Current PTO Balance"
dictLanguage.Add "Reason",				"Reason"
dictLanguage.Add "Approved",			"Approved"
dictLanguage.Add "Excused",				"Excused"
dictLanguage.Add "PTO_Approval1",		" , your PTO request was appproved.  A timecard has been added for you by the PTO system for the date(s) you requested PTO - " 
dictLanguage.Add "PTO_Approval2",		"hours.  If your PTO is canceled or rescheduled, please make sure that you edit/delete that timecard.  Thank you."
dictLanguage.Add "PTO_Approval3",		", your PTO request for "
dictLanguage.Add "PTO_Approval4",		" was not approved.  Please see your manager for more details."
dictLanguage.Add "PTO_Thankyou1",		"Thank you. The PTO request has been processed."
dictLanguage.Add "PTO_Error1",			"<br>You Must Select an Employee"
dictLanguage.Add "PTO_Notice1",			" completed a PTO form for the period "
dictLanguage.Add "PTO_Notice2",			" Please go to "
dictLanguage.Add "PTO_Notice3",			" to view the request and approve/dissaprove it."
dictLanguage.Add "PTO_PrelimNotice1",	", please go to "
dictLanguage.Add "PTO_PrelimNotice2",   "to complete the PTO form that has been initiated for the period "
dictLanguage.Add "View_PTO_By_Employee","View All Requests -- By Employee"
dictLanguage.Add "View_PTO_Not_Completed_By_Employee", "View All Requests Not Completed - By Employee"
dictLanguage.Add "View_PTO_For_Employee_Button", "View Employee's PTO Requests"
dictLanguage.Add "PTO_Requests_By_Employee", "PTO Request--By Employee"
dictLanguage.Add "From",				"From"
dictLanguage.Add "To",					"To"
dictLanguage.Add "PTO_Requests_By_Employee_Not_Completed", "PTO Requests--By Employee Not Completed"
dictLanguage.Add "PTO_Error2",			"<b>There are no PTO Requests for that employee!</b><BR><br>"
dictLanguage.Add "PTO_Request_For_Employee", "PTO Requests for Employee--"
dictLanguage.Add "PTO_Requests_By_Date","PTO Requests--By Date"
dictLanguage.Add "PTO_Updated",			"PTO Setting was updated"
dictLanguage.Add "PTO_Not_Updated",		"PTO Setting was not updated: "



	
'Reports
dictLanguage.Add "Which_Client",		"Which Client/Project"
dictLanguage.Add "All_Sites",			"All Clients/Projects"
dictLanguage.Add "Which_Project_Type",	"What type of Project"
dictLanguage.Add "All_Project_Types",	"All Project Types"
dictLanguage.Add "Which_Timecard_Type", "What type of Work"
dictLanguage.Add "All_Timecard_Types",	"All Work Types"
dictLanguage.Add "Which_Department",	"Which Department"
dictLanguage.Add "All_Departments",		"All Departments"
dictLanguage.Add "Which_Employee",		"Which Employee"
dictLanguage.Add "All_Employees",		"All Employees"
dictLanguage.Add "Which_Account_Rep",	"Which Account Rep"
dictLanguage.Add "All_Account_Reps",	"All Account Reps"
dictLanguage.Add "Error_ReportInvalidStart", "The Start Date was not a valid date!"
dictLanguage.Add "Error_ReportInvalidEnd", "The End Date was not a valid date!"
dictLanguage.Add "Since",				"Since"
dictLanguage.Add "Through",				"Through"
dictLanguage.Add "No_Report_Work",		"There has been no work for the search dates specified."
dictLanguage.Add "Billable_Hours",		"Billable Hours"
dictLanguage.Add "Non-Billable_Hours",	"Non-Billable Hours"
dictLanguage.Add "Total_Hours",			"Total Hours"
dictLanguage.Add "Value",				"Value"
dictLanguage.Add "Billable_Total",		"Billable Total"
dictLanguage.Add "Non-Billable_Total",	"Non-Billable Total"
dictLanguage.Add "Grand_Total",			"Grand Total"
dictLanguage.Add "Total_Cost",			"Total Cost"
dictLanguage.Add "Total_Value",			"Total Value"
dictLanguage.Add "Return_Work_Log_Form","Return to the Work Log Form"
dictLanguage.Add "Activity",			"Activity"
dictLanguage.Add "Production_Report_Grid", "Production Report Grid"
dictLanguage.Add "Client_Hours",		"Client Hours"
dictLanguage.Add "Today",				"Today"
dictLanguage.Add "Fri/Sat/Sun",			"Fri/Sat/Sun"
dictLanguage.Add "Y'day",				"Y'day"
dictLanguage.Add "This_Week",			"This<br>Week"
dictLanguage.Add "This_Month",			"This<Br>Month"
dictLanguage.Add "Last_Week",			"Last<br>Week"
dictLanguage.Add "Last_Month",			"Last<br>Month"
dictLanguage.Add "Goal",				"Goal"
dictLanguage.Add "diff",				"diff"
dictLanguage.Add "Download",			"Download"
dictLanguage.Add "Task_Hours_Assigned", "Task Hours Assigned"
dictLanguage.Add "Task_Inst_1",			"Below is a list of employees and the " & _
	"total number of estimated hours tasked to them minus the amount of hours " & _
	"they have already spent on those tasks."
dictLanguage.Add "Next_Week",			"Next Week"
dictLanguage.Add "No_Tasks_Assigned",	"No Tasks Assigned"
dictLanguage.Add "More_Time_Used",		"More time used on tasks than allocated"
	
'Repository
dictLanguage.Add "Rep_Inst_1",			"Click on the name of the document " & _
	"to view/download. Place your mouse over the document link for a description " & _
	"of the document.  Click on the contact name to view profile.  Select the " & _
	"&quot;X&quot; beside the file name to remove the document from the " & _
	"repository.  There will only be an &quot;X&quot; next to documents in " & _
	"which you are listed as the contact."
dictLanguage.Add "Return_Search",		"Return to Search"
dictLanguage.Add "Return_Document_Repository", "Return to the Document Repository Home"
dictLanguage.Add "Utilities",			"Utilities"
dictLanguage.Add "Document_Search",		"Document Search"
dictLanguage.Add "Rep_Inst_2",			"You can use keywords in the contact " & _
	"and file name fields if you know some of the name of the file or the " & _
	"person listed as contact for the document.  Click the ""Search"" button " & _
	"to see your results."	
dictLanguage.Add "Contacts",			"Contacts"
dictLanguage.Add "File_Name",			"File Name"

'## following section added in version 2.6.0
'Resources
dictLanguage.Add "Resources",			"Resources"
dictLanguage.Add "Add_New_Resource",	"Add New Resource"
dictLanguage.Add "Edit_Resource",		"Edit Resource"
dictLanguage.Add "Delete_Resource",		"Delete Resource"
dictLanguage.Add "Confirm_Delete_Resource", "Are you sure you want to delete this resource?"
dictLanguage.Add "Resource_ID",			"Resource ID"
dictLanguage.Add "Resource_Title",		"Resource Title"
dictLanguage.Add "Resource_URL",		"Resource URL"
dictLanguage.Add "Resource_Date",		"Resource Date"
dictLanguage.Add "Resource_Caption",	"Resource Caption"
dictLanguage.Add "Resource_Added",		"The resource was added."
dictLanguage.Add "Resource_Updated",	"The resource was updated."
dictLanguage.Add "Resource_Deleted",	"The resource was deleted."

	
'Tasks
dictLanguage.Add "Task_Details",		"Task Details"
dictLanguage.Add "Deleted_Task",		"The task has been deleted"
dictLanguage.Add "Estimated_Hours",		"Estimated Hours"
dictLanguage.Add "Error_TaskNoName",	"You forgot to input the task description!"
dictLanguage.Add "Error_TaskNoPriority","You forgot to input the task priority!"
dictLanguage.Add "Error_TaskNoAssignedBy", "You forgot to input the employee the task is assigned by!"
dictLanguage.Add "Error_TaskAssignedTo","You forgot to input the employee the task is assigned to!"
dictLanguage.Add "Error_TaskEstHours",  "You forgot to input the estimated hours!"
dictLanguage.Add "Error_TaskInvalidHours", "Please enter a valid number for the estimated hours!"
dictLanguage.Add "Error_TaskNoDateCreated", "You forgot to input the date created!"
dictLanguage.Add "Error_TaskInvalidDateCreated", "Please enter a valid date for the date created!"
dictLanguage.Add "Error_TaskNoDateDue", "You forgot to input the date due!"
dictLanguage.Add "Error_TaskInvalidDateDue", "Please enter a valid date for the date due!"
dictLanguage.Add "Error_TaskNoClient",	"You forgot to input the client!"
dictLanguage.Add "Error_TaskInvalidClient", "The Client you have selected is not " & _
	"active!<br>In order to enter a project for this client, you must first make " & _
	"the client active."
dictLanguage.Add "Error_TaskNoEmployee","You must choose an employee from the dropdown."
dictLanguage.Add "Error_TaskNoTasks",	"There are no current tasks for that employee!"
dictLanguage.Add "Undefined",			"Undefined"
dictLanguage.Add "Task_Inst_2",			"A task has been assigned or updated for you.  " & _
	"Please consult your task list for additional information."
dictLanguage.Add "Task_Inst_3",			"A new task has been added for you.  " & _
	"Please consult your task list for additional information."
dictLanguage.Add "Updated_Task",		"The Task was updated"
dictLanguage.Add "Added_Task",			"The Task was added"
dictLanguage.Add "Add_Another_Task",	"Add Another Task"
dictLanguage.Add "Select_One_Clients_Projects", "Select One (Clients Listed First, Then Projects)"
dictLanguage.Add "has_completed",		"has completed "
dictLanguage.Add "has_reopened",		"has reopened "
dictLanguage.Add "Intranet_Task",		"Project Task"
dictLanguage.Add "Task_Completed",		"Task Completed"
dictLanguage.Add "Task_Reopened",		"Task Reopened"
dictLanguage.Add "Task_Inst_4",			"The task was marked Complete by "
dictLanguage.Add "Task_Inst_5",			"The task was marked Reopened by "
dictLanguage.Add "Archived",			"Archived"
dictLanguage.Add "Task_Graph_View",		"Graph View of Current Tasks"
dictLanguage.Add "View_Tasks_Client",	"View Tasks For A Client"
dictLanguage.Add "View_All_Tasks",		"View All Tasks"
dictLanguage.Add "View_Tasks_Employee", "View Tasks for an Employee"
dictLanguage.Add "By_Assignor",			"By Assignor"
dictLanguage.Add "By_Employee",			"By Employee"
dictLanguage.Add "By_Client",			"By Client"
dictLanguage.Add "Tasks_List_Report",	"Tasks List Report"
dictLanguage.Add "Client/Project",		"Client/Project"
dictLanguage.Add "My_Tasks",			"My Tasks"
dictLanguage.Add "Create_Timecard",		"Create Timecard"
dictLanguage.Add "Do_It",				"Do it!"
dictLanguage.Add "Tasks_I_Assigned",	"Tasks I Assigned"
dictLanguage.Add "Tasks_For_Client",	"Tasks for Client"
dictLanguage.Add "tasks",				"tasks"
	
'timecards
dictLanguage.Add "Timecard_Details",	"Timecard Details"
dictLanguage.Add "Client/Project/Task", "Client/Project/Task"
dictLanguage.Add "Select_One_Clients_Projects_Tasks", "Select One (Clients Listed First, Then Projects, Then Task)"
dictLanguage.Add "Project_Phase",		"Project Phase"
dictLanguage.Add "Select_One_If_App",	"Select One (if applicable)"
dictLanguage.Add "Select_One",			"Select One"
dictLanguage.Add "Type_Of_Work",		"Type of Work"
dictLanguage.Add "Deleted_Timecard",	"The Timecard was deleted."
dictLanguage.Add "Add_Timecard",		"Add Timecard"
dictLanguage.Add "Reconciled",			"Reconciled"
dictLanguage.Add "Error_TimecardNoClient", "You Must Select a Client"
dictLanguage.Add "Error_TimecardNoWorkType", "You Must Select a Type of Work"
dictLanguage.Add "Error_TimecardNoTime", "You Must Enter the Number of " & _
	"Hours Worked -- It must be number, like 4.5 for 4 1/2"
dictLanguage.Add "Error_TimecardNoDate","You Must Enter a Date -- The date must be properly formated"
dictLanguage.Add "Error_TimecardNoDesc","You Must Enter a Description for Your Work"
dictLanguage.Add "Error_TimecardNoEmp", "You Must Select an Employee"
dictLanguage.Add "Updated_Timecard",	"The Timecard was updated."
dictLanguage.Add "Added_Timecard",		"The Timecard was added."
dictLanguage.Add "Error_TimecardInvalidClient", "The Client you have selected is not " & _
	"active!<br>In order to enter a timecard for this client, you must first " & _
	"make the client active."
dictLanguage.Add "Last_30_Days",		"last 30 days"
dictLanguage.Add "Total_Hours_Today",	"Total Hours Today"
	
'timesheets
dictLanguage.Add "Timesheet_Details",	"Timesheet Details"
dictLanguage.Add "In_1",				"In 1"
dictLanguage.Add "In_2",				"In 2"
dictLanguage.Add "Out_1",				"Out 1"
dictLanguage.Add "Out_2",				"Out 2"
dictLanguage.Add "Error_TimesheetNoDate", "Please enter a date for date worked!"
dictLanguage.Add "Error_TimesheetInvalidDate", "Please enter a valid date for date worked!"
dictLanguage.Add "Error_TimesheetNoEmp","Please select an employee."	
dictLanguage.Add "Error_TimesheetNoPayPeriod", "There is no current pay period listed " & _
	"in the database.  Please contact the project administrator to update the pay periods."	
dictLanguage.Add "Timesheet_For",		"Timesheet for"
dictLanguage.Add "For_PayPeriod_Beginning", "for pay period Beginning"
dictLanguage.Add "Timesheet_Inst_1",	"Records with asterisks(*) are incomplete.  " & _
	"The employee must correct them."
dictLanguage.Add "View_Timesheet_History", "View Employee's Time Sheet History"
dictLanguage.Add "Workday_In_Progress",	"WorkDay In Progress"
dictLanguage.Add "Timesheet_History",	"Timesheet History"
dictLanguage.Add "Timesheet_For_Period","Time Sheet for the Period"
dictLanguage.Add "No_Timesheets_Archived", "There are not any Time Sheets archived for"
	
%>


